version: 2.1

references:
    set_npm_token: &set_npm_token
        run:
            name: Add NPM auth token file
            command: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
    build:
        docker:
            - image: circleci/node:8

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-1-{{ checksum "package-lock.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-1-{{ checksum "package-lock.json" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - package-lock.json
                      - src

    eslint:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run eslint

    publish:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - *set_npm_token

            - attach_workspace:
                  at: "."

            - run: npm publish || exit 0

    prettier:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run prettier

    test:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run test -- --coverage

    tsc:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run tsc

            - persist_to_workspace:
                  root: "."
                  paths:
                      - src

workflows:
    version: 2
    commit:
        jobs:
            - build
            - eslint:
                  requires:
                      - build
            - publish:
                  filters:
                      branches:
                          only: master
                  requires:
                      - tsc
            - prettier:
                  requires:
                      - build
            - test:
                  requires:
                      - build
            - tsc:
                  requires:
                      - build
